version: '3.7'
services:
  backend:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: yarn start:prod
    depends_on:
      - db
  db:
    container_name: postgresdb
    image: postgres
    environment:
      URI: ${DB_URI}
    ports:
      - 5432:5432
    volumes:
      - ./data:/usr/src/app
